/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package tanksimulator;

import javax.swing.JOptionPane;

/**
 *
 * @author Deangelo
 */
public class MainForm extends javax.swing.JFrame {

    FormManager formManager;
    SimulatorConection simulatorConection;
    GeradorDeSinais geradorDeSinais;
    GrafoManager grafoManager;
    Thread t;
    Thread TGraphics;
    //transit
    //0 - tempo atual
    //1 - valor da tensão enviada
    //2 - nivel do tanque 1
    //3 - semaforo utilizado entre simulatorConection e GrafoManager.
    //4 - variavel de controle para a trava supeior
    //5 - nivel do tanque 2
    //6 - nivel do tanque 3
    //7 - nivel do tanque 4
    //8 - nivel do tanque 5
    //9 - nivel do tanque 6
    //10 - nivel do tanque 7
    //11 - nivel do tanque 8
    //12 - erro Volts
    //13 - erro Altura
    //14 - valor setpoint
    //15 - malhaAberta < 1...malha fechada > 1
    //16 - flag que indica se o canal 2 esta sendo usado
    //17 - variavel de controle para a trava inferior
    //18 - variavel de controle para a trava de entumpimento
    double transit[];
    boolean aux;

    public MainForm() {
        initComponents();

        this.Radio_OpenSytem.setSelected(true);
        this.channel1_Read.setSelected(true);
        this.channel1_Write.setSelected(true);

        this.lbl_setPoint.setVisible(false);
        this.txtF_setPoint.setVisible(false);
        //this.lbl_amplitude.setVisible(false);
        this.lbl_offset.setVisible(false);
        this.lbl_periodo.setVisible(false);
        //this.txtF_amplitude.setVisible(false);
        this.txtF_offset.setVisible(false);
        this.txtF_Periodo.setVisible(false);

        this.txtF_Periodo.setText("20.0");
        this.txtF_offset.setText("0.0");
        this.txtF_amplitude.setText("0.0");
        this.txtF_fatorAceleracao.setText("0");
        this.txtF_ip.setText("localhost");
        this.txtF_porta.setText("20081");

        this.transit = new double[19];
        this.transit[3] = 2;
        this.transit[15] = 0;

        this.grafoManager = new GrafoManager(this.pnl_GraficoSinal, this.pnl_GraficoALtura, this.transit, this.pnl_Grafico_SinalApenas,
                this.txtF_valorTensao, this.txtF_valorNivel, this.txtF_tempo, this.txtF_fatorAceleracao, this.txtF_valorNivelTanque2,
                this.pnl_nivelTanque2, this.pnl_erroAltura, this.txtF_errorAltura, this.pnl_grafico_todos);
       
        this.TGraphics = new Thread(this.grafoManager);
        this.TGraphics.start();

        this.formManager = new FormManager();
        //this.simulatorConection = new SimulatorConection("localhost", 20081, 0, 0, this.txtF_amplitude, 
        //        this.txtF_offset, this.txtF_Periodo, 0, transit);
        this.simulatorConection = new SimulatorConection();

        //this.simulatorConection.setTensionValue(1);
        this.t = new Thread(simulatorConection);
        this.t.setPriority(Thread.MAX_PRIORITY);
        this.t.start();



        aux = false;
     

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        panel_canalDeLeitura = new javax.swing.JPanel();
        lbl_canalDeLeitura = new javax.swing.JLabel();
        channel1_Read = new javax.swing.JRadioButton();
        channel2_Read = new javax.swing.JRadioButton();
        channel3_Read = new javax.swing.JRadioButton();
        channel4_Read = new javax.swing.JRadioButton();
        channel5_Read = new javax.swing.JRadioButton();
        channel6_Read = new javax.swing.JRadioButton();
        channel7_Read = new javax.swing.JRadioButton();
        channel8_Read = new javax.swing.JRadioButton();
        panel_Escrita = new javax.swing.JPanel();
        lbl_canalDeEscrita = new javax.swing.JLabel();
        channel1_Write = new javax.swing.JRadioButton();
        channel2_Write = new javax.swing.JRadioButton();
        channel3_Write = new javax.swing.JRadioButton();
        channel4_Write = new javax.swing.JRadioButton();
        channel5_Write = new javax.swing.JRadioButton();
        channel6_Write = new javax.swing.JRadioButton();
        channel7_Write = new javax.swing.JRadioButton();
        channel8_Write = new javax.swing.JRadioButton();
        pnl_malha = new javax.swing.JPanel();
        lbl_Malha = new javax.swing.JLabel();
        Radio_OpenSytem = new javax.swing.JRadioButton();
        Radio_ClosedSystem = new javax.swing.JRadioButton();
        lbl_sinal = new javax.swing.JLabel();
        cmbx_tipoDeSinal = new javax.swing.JComboBox();
        lbl_amplitude = new javax.swing.JLabel();
        lbl_offset = new javax.swing.JLabel();
        lbl_periodo = new javax.swing.JLabel();
        txtF_amplitude = new javax.swing.JTextField();
        txtF_offset = new javax.swing.JTextField();
        txtF_Periodo = new javax.swing.JTextField();
        btn_refresh = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jTabbedPane2 = new javax.swing.JTabbedPane();
        pnl_grafico_aba1 = new javax.swing.JPanel();
        pnl_Grafico_fundoAba1 = new javax.swing.JPanel();
        pnl_GraficoSinal = new javax.swing.JPanel();
        pnl_GraficoALtura = new javax.swing.JPanel();
        pnl_nivelTanque2 = new javax.swing.JPanel();
        pnl_erroAltura = new javax.swing.JPanel();
        pnl_grafico_todos = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        pnl_Grafico_fundoAba2 = new javax.swing.JPanel();
        pnl_Grafico_SinalApenas = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        lbl_tensao = new javax.swing.JLabel();
        txtF_valorTensao = new javax.swing.JTextField();
        lbl_nivel = new javax.swing.JLabel();
        txtF_valorNivel = new javax.swing.JTextField();
        lbl_tempo = new javax.swing.JLabel();
        txtF_tempo = new javax.swing.JTextField();
        lbl_saida_tensao_volts = new javax.swing.JLabel();
        lbl_saida_nivel_centimetro = new javax.swing.JLabel();
        lbl_saida_tempo_segundo = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtF_errorAltura = new javax.swing.JTextField();
        lbl_saida_erro_centimetro = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtF_valorNivelTanque2 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        lbl_fatorDeAceleracao = new javax.swing.JLabel();
        txtF_fatorAceleracao = new javax.swing.JTextField();
        lbl_grafico = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        lbl_ONOFF = new javax.swing.JLabel();
        lbl_configuracoes_ip = new javax.swing.JLabel();
        txtF_ip = new javax.swing.JTextField();
        lbl_configuracoes_porta = new javax.swing.JLabel();
        txtF_porta = new javax.swing.JTextField();
        lbl_configuracoes_conexao = new javax.swing.JLabel();
        lbl_setPoint = new javax.swing.JLabel();
        txtF_setPoint = new javax.swing.JTextField();
        jPanel6 = new javax.swing.JPanel();
        jPanel7 = new javax.swing.JPanel();
        jPanel8 = new javax.swing.JPanel();
        lbl_conexao_leitura0 = new javax.swing.JLabel();
        lbl_conexao_leitura1 = new javax.swing.JLabel();
        lbl_conexao_leitura2 = new javax.swing.JLabel();
        lbl_conexao_leitura3 = new javax.swing.JLabel();
        lbl_conexao_leitura4 = new javax.swing.JLabel();
        lbl_conexao_leitura5 = new javax.swing.JLabel();
        lbl_conexao_leitura6 = new javax.swing.JLabel();
        lbl_conexao_leitura7 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        lbl_conexao_Escrita0 = new javax.swing.JLabel();
        lbl_conexao_Escrita1 = new javax.swing.JLabel();
        lbl_conexao_Escrita2 = new javax.swing.JLabel();
        lbl_conexao_Escrita3 = new javax.swing.JLabel();
        lbl_conexao_Escrita4 = new javax.swing.JLabel();
        lbl_conexao_Escrita5 = new javax.swing.JLabel();
        lbl_conexao_Escrita6 = new javax.swing.JLabel();
        lbl_conexao_Escrita7 = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        jMenu2 = new javax.swing.JMenu();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setBackground(new java.awt.Color(204, 255, 255));

        panel_canalDeLeitura.setBackground(new java.awt.Color(204, 255, 204));
        panel_canalDeLeitura.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lbl_canalDeLeitura.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_canalDeLeitura.setText("Canal de Leitura");

        channel1_Read.setBackground(new java.awt.Color(204, 255, 204));
        channel1_Read.setText("0");
        channel1_Read.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                channel1_ReadActionPerformed(evt);
            }
        });

        channel2_Read.setBackground(new java.awt.Color(204, 255, 204));
        channel2_Read.setText("1");
        channel2_Read.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                channel2_ReadActionPerformed(evt);
            }
        });

        channel3_Read.setBackground(new java.awt.Color(204, 255, 204));
        channel3_Read.setText("2");
        channel3_Read.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                channel3_ReadActionPerformed(evt);
            }
        });

        channel4_Read.setBackground(new java.awt.Color(204, 255, 204));
        channel4_Read.setText("3");
        channel4_Read.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                channel4_ReadActionPerformed(evt);
            }
        });

        channel5_Read.setBackground(new java.awt.Color(204, 255, 204));
        channel5_Read.setText("4");
        channel5_Read.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                channel5_ReadActionPerformed(evt);
            }
        });

        channel6_Read.setBackground(new java.awt.Color(204, 255, 204));
        channel6_Read.setText("6");
        channel6_Read.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                channel6_ReadActionPerformed(evt);
            }
        });

        channel7_Read.setBackground(new java.awt.Color(204, 255, 204));
        channel7_Read.setText("6");
        channel7_Read.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                channel7_ReadActionPerformed(evt);
            }
        });

        channel8_Read.setBackground(new java.awt.Color(204, 255, 204));
        channel8_Read.setText("7");
        channel8_Read.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                channel8_ReadActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_canalDeLeituraLayout = new javax.swing.GroupLayout(panel_canalDeLeitura);
        panel_canalDeLeitura.setLayout(panel_canalDeLeituraLayout);
        panel_canalDeLeituraLayout.setHorizontalGroup(
            panel_canalDeLeituraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_canalDeLeituraLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_canalDeLeituraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_canalDeLeituraLayout.createSequentialGroup()
                        .addComponent(channel4_Read)
                        .addGap(18, 18, 18)
                        .addComponent(channel8_Read))
                    .addGroup(panel_canalDeLeituraLayout.createSequentialGroup()
                        .addComponent(channel3_Read)
                        .addGap(18, 18, 18)
                        .addComponent(channel7_Read))
                    .addGroup(panel_canalDeLeituraLayout.createSequentialGroup()
                        .addComponent(channel1_Read)
                        .addGap(18, 18, 18)
                        .addComponent(channel5_Read))
                    .addGroup(panel_canalDeLeituraLayout.createSequentialGroup()
                        .addComponent(channel2_Read)
                        .addGap(18, 18, 18)
                        .addComponent(channel6_Read))
                    .addComponent(lbl_canalDeLeitura))
                .addGap(8, 10, Short.MAX_VALUE))
        );
        panel_canalDeLeituraLayout.setVerticalGroup(
            panel_canalDeLeituraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_canalDeLeituraLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_canalDeLeitura)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_canalDeLeituraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(channel1_Read)
                    .addComponent(channel5_Read))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_canalDeLeituraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(channel2_Read)
                    .addComponent(channel6_Read))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_canalDeLeituraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(channel3_Read)
                    .addComponent(channel7_Read))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_canalDeLeituraLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(channel4_Read)
                    .addComponent(channel8_Read))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        panel_Escrita.setBackground(new java.awt.Color(204, 255, 204));
        panel_Escrita.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lbl_canalDeEscrita.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_canalDeEscrita.setText("Canal de Escrita");

        channel1_Write.setBackground(new java.awt.Color(204, 255, 204));
        channel1_Write.setText("0");
        channel1_Write.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                channel1_WriteActionPerformed(evt);
            }
        });

        channel2_Write.setBackground(new java.awt.Color(204, 255, 204));
        channel2_Write.setText("1");
        channel2_Write.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                channel2_WriteActionPerformed(evt);
            }
        });

        channel3_Write.setBackground(new java.awt.Color(204, 255, 204));
        channel3_Write.setText("2");
        channel3_Write.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                channel3_WriteActionPerformed(evt);
            }
        });

        channel4_Write.setBackground(new java.awt.Color(204, 255, 204));
        channel4_Write.setText("3");
        channel4_Write.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                channel4_WriteActionPerformed(evt);
            }
        });

        channel5_Write.setBackground(new java.awt.Color(204, 255, 204));
        channel5_Write.setText("4");
        channel5_Write.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                channel5_WriteActionPerformed(evt);
            }
        });

        channel6_Write.setBackground(new java.awt.Color(204, 255, 204));
        channel6_Write.setText("5");
        channel6_Write.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                channel6_WriteActionPerformed(evt);
            }
        });

        channel7_Write.setBackground(new java.awt.Color(204, 255, 204));
        channel7_Write.setText("6");
        channel7_Write.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                channel7_WriteActionPerformed(evt);
            }
        });

        channel8_Write.setBackground(new java.awt.Color(204, 255, 204));
        channel8_Write.setText("7");
        channel8_Write.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                channel8_WriteActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout panel_EscritaLayout = new javax.swing.GroupLayout(panel_Escrita);
        panel_Escrita.setLayout(panel_EscritaLayout);
        panel_EscritaLayout.setHorizontalGroup(
            panel_EscritaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_EscritaLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(panel_EscritaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(panel_EscritaLayout.createSequentialGroup()
                        .addComponent(channel4_Write)
                        .addGap(18, 18, 18)
                        .addComponent(channel8_Write))
                    .addGroup(panel_EscritaLayout.createSequentialGroup()
                        .addComponent(channel3_Write)
                        .addGap(18, 18, 18)
                        .addComponent(channel7_Write))
                    .addGroup(panel_EscritaLayout.createSequentialGroup()
                        .addComponent(channel1_Write)
                        .addGap(18, 18, 18)
                        .addComponent(channel5_Write))
                    .addGroup(panel_EscritaLayout.createSequentialGroup()
                        .addComponent(channel2_Write)
                        .addGap(18, 18, 18)
                        .addComponent(channel6_Write))
                    .addComponent(lbl_canalDeEscrita))
                .addGap(8, 70, Short.MAX_VALUE))
        );
        panel_EscritaLayout.setVerticalGroup(
            panel_EscritaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panel_EscritaLayout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_canalDeEscrita)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(panel_EscritaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(channel1_Write)
                    .addComponent(channel5_Write))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_EscritaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(channel2_Write)
                    .addComponent(channel6_Write))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_EscritaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(channel3_Write)
                    .addComponent(channel7_Write))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(panel_EscritaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(channel4_Write)
                    .addComponent(channel8_Write))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pnl_malha.setBackground(new java.awt.Color(204, 255, 204));
        pnl_malha.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(0, 0, 0), 1, true));

        lbl_Malha.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_Malha.setText("Malha");

        Radio_OpenSytem.setBackground(new java.awt.Color(204, 255, 204));
        Radio_OpenSytem.setText("Aberta");
        Radio_OpenSytem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Radio_OpenSytemActionPerformed(evt);
            }
        });

        Radio_ClosedSystem.setBackground(new java.awt.Color(204, 255, 204));
        Radio_ClosedSystem.setText("Fechada");
        Radio_ClosedSystem.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                Radio_ClosedSystemActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout pnl_malhaLayout = new javax.swing.GroupLayout(pnl_malha);
        pnl_malha.setLayout(pnl_malhaLayout);
        pnl_malhaLayout.setHorizontalGroup(
            pnl_malhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_malhaLayout.createSequentialGroup()
                .addGroup(pnl_malhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(pnl_malhaLayout.createSequentialGroup()
                        .addGap(35, 35, 35)
                        .addComponent(lbl_Malha))
                    .addGroup(pnl_malhaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Radio_OpenSytem))
                    .addGroup(pnl_malhaLayout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(Radio_ClosedSystem)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        pnl_malhaLayout.setVerticalGroup(
            pnl_malhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_malhaLayout.createSequentialGroup()
                .addComponent(lbl_Malha)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Radio_OpenSytem)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(Radio_ClosedSystem)
                .addGap(0, 8, Short.MAX_VALUE))
        );

        lbl_sinal.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_sinal.setText("Sinal");

        cmbx_tipoDeSinal.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Degrau", "Senóide", "Quadrada", "Dente de Serra", "Aleatório" }));
        cmbx_tipoDeSinal.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                cmbx_tipoDeSinalItemStateChanged(evt);
            }
        });

        lbl_amplitude.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_amplitude.setText("Amplitude");

        lbl_offset.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_offset.setText("Offset");

        lbl_periodo.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_periodo.setText("Período");

        txtF_amplitude.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtF_amplitudeKeyReleased(evt);
            }
        });

        txtF_offset.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtF_offsetKeyReleased(evt);
            }
        });

        txtF_Periodo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtF_PeriodoKeyReleased(evt);
            }
        });

        btn_refresh.setText("Conectar");
        btn_refresh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                btn_refreshMouseClicked(evt);
            }
        });

        jButton1.setText("ON/OFF");
        jButton1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton1MouseClicked(evt);
            }
        });

        pnl_grafico_aba1.setForeground(new java.awt.Color(153, 255, 255));

        pnl_Grafico_fundoAba1.setBackground(new java.awt.Color(204, 255, 255));
        pnl_Grafico_fundoAba1.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        pnl_GraficoSinal.setBackground(new java.awt.Color(255, 153, 153));
        pnl_GraficoSinal.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl_GraficoSinal.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_GraficoSinalMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl_GraficoSinalLayout = new javax.swing.GroupLayout(pnl_GraficoSinal);
        pnl_GraficoSinal.setLayout(pnl_GraficoSinalLayout);
        pnl_GraficoSinalLayout.setHorizontalGroup(
            pnl_GraficoSinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnl_GraficoSinalLayout.setVerticalGroup(
            pnl_GraficoSinalLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnl_GraficoALtura.setBackground(new java.awt.Color(255, 102, 102));
        pnl_GraficoALtura.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnl_GraficoALturaLayout = new javax.swing.GroupLayout(pnl_GraficoALtura);
        pnl_GraficoALtura.setLayout(pnl_GraficoALturaLayout);
        pnl_GraficoALturaLayout.setHorizontalGroup(
            pnl_GraficoALturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnl_GraficoALturaLayout.setVerticalGroup(
            pnl_GraficoALturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );

        pnl_nivelTanque2.setBackground(new java.awt.Color(51, 255, 0));
        pnl_nivelTanque2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnl_nivelTanque2Layout = new javax.swing.GroupLayout(pnl_nivelTanque2);
        pnl_nivelTanque2.setLayout(pnl_nivelTanque2Layout);
        pnl_nivelTanque2Layout.setHorizontalGroup(
            pnl_nivelTanque2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 202, Short.MAX_VALUE)
        );
        pnl_nivelTanque2Layout.setVerticalGroup(
            pnl_nivelTanque2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        pnl_erroAltura.setBackground(new java.awt.Color(153, 153, 255));
        pnl_erroAltura.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnl_erroAlturaLayout = new javax.swing.GroupLayout(pnl_erroAltura);
        pnl_erroAltura.setLayout(pnl_erroAlturaLayout);
        pnl_erroAlturaLayout.setHorizontalGroup(
            pnl_erroAlturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 202, Short.MAX_VALUE)
        );
        pnl_erroAlturaLayout.setVerticalGroup(
            pnl_erroAlturaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 151, Short.MAX_VALUE)
        );

        pnl_grafico_todos.setBackground(new java.awt.Color(255, 255, 51));
        pnl_grafico_todos.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        pnl_grafico_todos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                pnl_grafico_todosMouseClicked(evt);
            }
        });

        javax.swing.GroupLayout pnl_grafico_todosLayout = new javax.swing.GroupLayout(pnl_grafico_todos);
        pnl_grafico_todos.setLayout(pnl_grafico_todosLayout);
        pnl_grafico_todosLayout.setHorizontalGroup(
            pnl_grafico_todosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );
        pnl_grafico_todosLayout.setVerticalGroup(
            pnl_grafico_todosLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 155, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnl_Grafico_fundoAba1Layout = new javax.swing.GroupLayout(pnl_Grafico_fundoAba1);
        pnl_Grafico_fundoAba1.setLayout(pnl_Grafico_fundoAba1Layout);
        pnl_Grafico_fundoAba1Layout.setHorizontalGroup(
            pnl_Grafico_fundoAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Grafico_fundoAba1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_Grafico_fundoAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(pnl_Grafico_fundoAba1Layout.createSequentialGroup()
                        .addGroup(pnl_Grafico_fundoAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnl_nivelTanque2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnl_GraficoSinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(9, 9, 9)
                        .addGroup(pnl_Grafico_fundoAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(pnl_erroAltura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(pnl_GraficoALtura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addComponent(pnl_grafico_todos, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(239, Short.MAX_VALUE))
        );
        pnl_Grafico_fundoAba1Layout.setVerticalGroup(
            pnl_Grafico_fundoAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Grafico_fundoAba1Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(pnl_Grafico_fundoAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnl_GraficoALtura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_GraficoSinal, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(11, 11, 11)
                .addGroup(pnl_Grafico_fundoAba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(pnl_erroAltura, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(pnl_nivelTanque2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(pnl_grafico_todos, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(122, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout pnl_grafico_aba1Layout = new javax.swing.GroupLayout(pnl_grafico_aba1);
        pnl_grafico_aba1.setLayout(pnl_grafico_aba1Layout);
        pnl_grafico_aba1Layout.setHorizontalGroup(
            pnl_grafico_aba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_Grafico_fundoAba1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        pnl_grafico_aba1Layout.setVerticalGroup(
            pnl_grafico_aba1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnl_grafico_aba1Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(pnl_Grafico_fundoAba1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jTabbedPane2.addTab("Gráficos", pnl_grafico_aba1);

        pnl_Grafico_fundoAba2.setBackground(new java.awt.Color(204, 255, 255));
        pnl_Grafico_fundoAba2.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        pnl_Grafico_SinalApenas.setBackground(new java.awt.Color(255, 51, 51));
        pnl_Grafico_SinalApenas.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        javax.swing.GroupLayout pnl_Grafico_SinalApenasLayout = new javax.swing.GroupLayout(pnl_Grafico_SinalApenas);
        pnl_Grafico_SinalApenas.setLayout(pnl_Grafico_SinalApenasLayout);
        pnl_Grafico_SinalApenasLayout.setHorizontalGroup(
            pnl_Grafico_SinalApenasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 642, Short.MAX_VALUE)
        );
        pnl_Grafico_SinalApenasLayout.setVerticalGroup(
            pnl_Grafico_SinalApenasLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 195, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout pnl_Grafico_fundoAba2Layout = new javax.swing.GroupLayout(pnl_Grafico_fundoAba2);
        pnl_Grafico_fundoAba2.setLayout(pnl_Grafico_fundoAba2Layout);
        pnl_Grafico_fundoAba2Layout.setHorizontalGroup(
            pnl_Grafico_fundoAba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Grafico_fundoAba2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_Grafico_SinalApenas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        pnl_Grafico_fundoAba2Layout.setVerticalGroup(
            pnl_Grafico_fundoAba2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnl_Grafico_fundoAba2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(pnl_Grafico_SinalApenas, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(403, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_Grafico_fundoAba2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(pnl_Grafico_fundoAba2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane2.addTab("Sinal", jPanel2);

        jPanel3.setBackground(new java.awt.Color(204, 255, 255));
        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Saida", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Aharoni", 3, 14))); // NOI18N

        lbl_tensao.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbl_tensao.setText("Tensão");

        txtF_valorTensao.setEnabled(false);

        lbl_nivel.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbl_nivel.setText("Nível 1");

        txtF_valorNivel.setEditable(false);
        txtF_valorNivel.setEnabled(false);

        lbl_tempo.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        lbl_tempo.setText("Tempo");

        txtF_tempo.setEditable(false);
        txtF_tempo.setEnabled(false);

        lbl_saida_tensao_volts.setText("V");

        lbl_saida_nivel_centimetro.setText("cm");

        lbl_saida_tempo_segundo.setText("s");

        jLabel6.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        jLabel6.setText("Erro");

        txtF_errorAltura.setFont(new java.awt.Font("Times New Roman", 1, 11)); // NOI18N
        txtF_errorAltura.setEnabled(false);

        lbl_saida_erro_centimetro.setText("cm");

        jLabel2.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        jLabel2.setText("Nível 2");

        txtF_valorNivelTanque2.setEnabled(false);

        jLabel3.setText("cm");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lbl_tensao)
                                    .addComponent(lbl_nivel))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtF_valorNivel, javax.swing.GroupLayout.DEFAULT_SIZE, 63, Short.MAX_VALUE)
                                    .addComponent(txtF_valorTensao)))
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addComponent(jLabel6)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 22, Short.MAX_VALUE)
                                .addComponent(txtF_errorAltura, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_saida_tensao_volts)
                            .addComponent(lbl_saida_nivel_centimetro)
                            .addComponent(lbl_saida_erro_centimetro)))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(lbl_tempo)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addComponent(txtF_tempo, javax.swing.GroupLayout.PREFERRED_SIZE, 61, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(lbl_saida_tempo_segundo))
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel2)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(txtF_valorNivelTanque2, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel3)))
                .addContainerGap(31, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_tensao)
                    .addComponent(txtF_valorTensao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_saida_tensao_volts))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_nivel)
                    .addComponent(txtF_valorNivel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lbl_saida_nivel_centimetro))
                .addGap(3, 3, 3)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(txtF_valorNivelTanque2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_saida_tempo_segundo)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lbl_tempo)
                        .addComponent(txtF_tempo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(txtF_errorAltura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(lbl_saida_erro_centimetro))
                    .addComponent(jLabel6))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel4.setBackground(new java.awt.Color(204, 255, 255));
        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Configurações", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Andalus", 3, 14))); // NOI18N

        lbl_fatorDeAceleracao.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbl_fatorDeAceleracao.setText("Fator de Delay");

        lbl_grafico.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbl_grafico.setText("Limpar Gráfico");

        jButton2.setText("Ok");
        jButton2.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jButton2MouseClicked(evt);
            }
        });

        lbl_ONOFF.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lbl_ONOFF.setText("Sistema Desligada");

        lbl_configuracoes_ip.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbl_configuracoes_ip.setText("IP");

        lbl_configuracoes_porta.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        lbl_configuracoes_porta.setText("Porta");

        lbl_configuracoes_conexao.setFont(new java.awt.Font("Tahoma", 3, 12)); // NOI18N
        lbl_configuracoes_conexao.setText("Sistema Desconectado");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_grafico, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(lbl_fatorDeAceleracao, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtF_fatorAceleracao, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton2)))
                    .addComponent(lbl_ONOFF, javax.swing.GroupLayout.PREFERRED_SIZE, 147, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(lbl_configuracoes_ip)
                            .addComponent(lbl_configuracoes_porta))
                        .addGap(35, 35, 35)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtF_porta, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtF_ip, javax.swing.GroupLayout.PREFERRED_SIZE, 72, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addComponent(lbl_configuracoes_conexao))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_fatorDeAceleracao)
                    .addComponent(txtF_fatorAceleracao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_grafico)
                    .addComponent(jButton2))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_configuracoes_ip)
                    .addComponent(txtF_ip, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lbl_configuracoes_porta)
                    .addComponent(txtF_porta, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 14, Short.MAX_VALUE)
                .addComponent(lbl_ONOFF)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_configuracoes_conexao)
                .addGap(12, 12, 12))
        );

        lbl_setPoint.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        lbl_setPoint.setText("setPoint");

        txtF_setPoint.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtF_setPointKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(34, 34, 34)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(lbl_periodo, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_offset, javax.swing.GroupLayout.PREFERRED_SIZE, 64, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_amplitude, javax.swing.GroupLayout.PREFERRED_SIZE, 86, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(lbl_sinal, javax.swing.GroupLayout.PREFERRED_SIZE, 44, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(cmbx_tipoDeSinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 31, Short.MAX_VALUE)
                                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(lbl_setPoint)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(txtF_setPoint, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(txtF_amplitude, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(panel_canalDeLeitura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addComponent(pnl_malha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addComponent(txtF_offset, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtF_Periodo, javax.swing.GroupLayout.PREFERRED_SIZE, 39, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(44, 44, 44)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btn_refresh)
                            .addComponent(panel_Escrita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jTabbedPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 673, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel1Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(panel_Escrita, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(panel_canalDeLeitura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(pnl_malha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel1Layout.createSequentialGroup()
                                .addComponent(btn_refresh)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jButton1)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_sinal)
                            .addComponent(cmbx_tipoDeSinal, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_amplitude)
                            .addComponent(txtF_amplitude, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lbl_setPoint)
                            .addComponent(txtF_setPoint, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(7, 7, 7)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_offset)
                            .addComponent(txtF_offset, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lbl_periodo)
                            .addComponent(txtF_Periodo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jTabbedPane2))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Sistema", jPanel1);

        jPanel6.setBackground(new java.awt.Color(204, 255, 255));

        jPanel7.setBackground(new java.awt.Color(204, 255, 204));
        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createEtchedBorder(), "Status da Conexão", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 14))); // NOI18N

        jPanel8.setBackground(new java.awt.Color(204, 255, 204));
        jPanel8.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Leitura", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        lbl_conexao_leitura0.setText("Canal 0: Desabilitado");

        lbl_conexao_leitura1.setText("Canal 1: Desabilitado");

        lbl_conexao_leitura2.setText("Canal 2: Desabilitado");

        lbl_conexao_leitura3.setText("Canal 3: Desabilitado");

        lbl_conexao_leitura4.setText("Canal 4: Desabilitado");

        lbl_conexao_leitura5.setText("Canal 5: Desabilitado");

        lbl_conexao_leitura6.setText("Canal 6: Desabilitado");

        lbl_conexao_leitura7.setText("Canal 7: Desabilitado");

        javax.swing.GroupLayout jPanel8Layout = new javax.swing.GroupLayout(jPanel8);
        jPanel8.setLayout(jPanel8Layout);
        jPanel8Layout.setHorizontalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_conexao_leitura0)
                    .addComponent(lbl_conexao_leitura1)
                    .addComponent(lbl_conexao_leitura2)
                    .addComponent(lbl_conexao_leitura3)
                    .addComponent(lbl_conexao_leitura4)
                    .addComponent(lbl_conexao_leitura5)
                    .addComponent(lbl_conexao_leitura6)
                    .addComponent(lbl_conexao_leitura7))
                .addContainerGap(87, Short.MAX_VALUE))
        );
        jPanel8Layout.setVerticalGroup(
            jPanel8Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel8Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_conexao_leitura0)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_conexao_leitura1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_conexao_leitura2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_conexao_leitura3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_conexao_leitura4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_conexao_leitura5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_conexao_leitura6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_conexao_leitura7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jPanel9.setBackground(new java.awt.Color(204, 255, 204));
        jPanel9.setBorder(javax.swing.BorderFactory.createTitledBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)), "Escrita", javax.swing.border.TitledBorder.DEFAULT_JUSTIFICATION, javax.swing.border.TitledBorder.DEFAULT_POSITION, new java.awt.Font("Tahoma", 1, 12))); // NOI18N

        lbl_conexao_Escrita0.setText("Canal 0: Desabilitado");

        lbl_conexao_Escrita1.setText("Canal 1: Desabilitado");

        lbl_conexao_Escrita2.setText("Canal 2: Desabilitado");

        lbl_conexao_Escrita3.setText("Canal 3: Desabilitado");

        lbl_conexao_Escrita4.setText("Canal 4: Desabilitado");

        lbl_conexao_Escrita5.setText("Canal 5: Desabilitado");

        lbl_conexao_Escrita6.setText("Canal 6: Desabilitado");

        lbl_conexao_Escrita7.setText("Canal 7: Desabilitado");

        javax.swing.GroupLayout jPanel9Layout = new javax.swing.GroupLayout(jPanel9);
        jPanel9.setLayout(jPanel9Layout);
        jPanel9Layout.setHorizontalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lbl_conexao_Escrita0)
                    .addComponent(lbl_conexao_Escrita1)
                    .addComponent(lbl_conexao_Escrita2)
                    .addComponent(lbl_conexao_Escrita3)
                    .addComponent(lbl_conexao_Escrita4)
                    .addComponent(lbl_conexao_Escrita5)
                    .addComponent(lbl_conexao_Escrita6)
                    .addComponent(lbl_conexao_Escrita7))
                .addContainerGap(99, Short.MAX_VALUE))
        );
        jPanel9Layout.setVerticalGroup(
            jPanel9Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel9Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(lbl_conexao_Escrita0)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_conexao_Escrita1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_conexao_Escrita2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_conexao_Escrita3)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_conexao_Escrita4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_conexao_Escrita5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_conexao_Escrita6)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lbl_conexao_Escrita7)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jPanel8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(jPanel9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(106, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(jPanel8, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel9, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(31, 31, 31)
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(479, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(353, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Conexão", jPanel6);

        jMenu1.setText("File");
        jMenuBar1.add(jMenu1);

        jMenu2.setText("Edit");
        jMenuBar1.add(jMenu2);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void Radio_ClosedSystemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Radio_ClosedSystemActionPerformed
        this.formManager.validateTypeSystem(Radio_OpenSytem, Radio_ClosedSystem, Radio_ClosedSystem);

        this.simulatorConection.setMalhaAberta(false);

        this.lbl_sinal.setVisible(false);
        this.lbl_periodo.setVisible(false);
        this.lbl_offset.setVisible(false);
        this.lbl_amplitude.setVisible(false);

        this.txtF_Periodo.setVisible(false);
        this.txtF_amplitude.setVisible(false);
        this.txtF_offset.setVisible(false);

        this.cmbx_tipoDeSinal.setVisible(false);

        this.lbl_setPoint.setVisible(true);
        this.txtF_setPoint.setVisible(true);
        this.transit[15] = 2;


    }//GEN-LAST:event_Radio_ClosedSystemActionPerformed

    private void channel1_WriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_channel1_WriteActionPerformed
        this.formManager.validateWriteChannel(channel1_Write, channel2_Write,
                channel3_Write, channel4_Write, channel5_Write, channel6_Write,
                channel7_Write, channel8_Write, channel1_Write);
    }//GEN-LAST:event_channel1_WriteActionPerformed

    private void channel2_WriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_channel2_WriteActionPerformed
        this.formManager.validateWriteChannel(channel1_Write, channel2_Write,
                channel3_Write, channel4_Write, channel5_Write, channel6_Write,
                channel7_Write, channel8_Write, channel2_Write);
    }//GEN-LAST:event_channel2_WriteActionPerformed

    private void channel3_WriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_channel3_WriteActionPerformed
        this.formManager.validateWriteChannel(channel1_Write, channel2_Write,
                channel3_Write, channel4_Write, channel5_Write, channel6_Write,
                channel7_Write, channel8_Write, channel3_Write);

    }//GEN-LAST:event_channel3_WriteActionPerformed

    private void channel4_WriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_channel4_WriteActionPerformed
        this.formManager.validateWriteChannel(channel1_Write, channel2_Write,
                channel3_Write, channel4_Write, channel5_Write, channel6_Write,
                channel7_Write, channel8_Write, channel4_Write);

    }//GEN-LAST:event_channel4_WriteActionPerformed

    private void channel5_WriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_channel5_WriteActionPerformed
        this.formManager.validateWriteChannel(channel1_Write, channel2_Write,
                channel3_Write, channel4_Write, channel5_Write, channel6_Write,
                channel7_Write, channel8_Write, channel5_Write);
    }//GEN-LAST:event_channel5_WriteActionPerformed

    private void channel6_WriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_channel6_WriteActionPerformed
        this.formManager.validateWriteChannel(channel1_Write, channel2_Write,
                channel3_Write, channel4_Write, channel5_Write, channel6_Write,
                channel7_Write, channel8_Write, channel6_Write);

    }//GEN-LAST:event_channel6_WriteActionPerformed

    private void channel7_WriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_channel7_WriteActionPerformed
        this.formManager.validateWriteChannel(channel1_Write, channel2_Write,
                channel3_Write, channel4_Write, channel5_Write, channel6_Write,
                channel7_Write, channel8_Write, channel7_Write);

    }//GEN-LAST:event_channel7_WriteActionPerformed

    private void channel8_WriteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_channel8_WriteActionPerformed
        this.formManager.validateWriteChannel(channel1_Write, channel2_Write,
                channel3_Write, channel4_Write, channel5_Write, channel6_Write,
                channel7_Write, channel8_Write, channel8_Write);

    }//GEN-LAST:event_channel8_WriteActionPerformed

    private void Radio_OpenSytemActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_Radio_OpenSytemActionPerformed
        this.formManager.validateTypeSystem(Radio_OpenSytem, Radio_ClosedSystem, Radio_OpenSytem);

        //System.out.println(Radio_OpenSytem.isSelected());
        //if (Radio_OpenSytem.isSelected()) {
        this.simulatorConection.setMalhaAberta(true);
        this.transit[15] = 0;
        this.lbl_setPoint.setVisible(false);
        this.txtF_setPoint.setVisible(false);

        this.lbl_sinal.setVisible(true);
        this.cmbx_tipoDeSinal.setVisible(true);
        this.lbl_amplitude.setVisible(true);
        this.txtF_amplitude.setVisible(true);


        if (this.simulatorConection.getSignalType() != 0) {
            this.lbl_periodo.setVisible(true);
            this.lbl_offset.setVisible(true);

            this.txtF_Periodo.setVisible(true);
            this.txtF_offset.setVisible(true);

        }
    }//GEN-LAST:event_Radio_OpenSytemActionPerformed

    private void cmbx_tipoDeSinalItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_cmbx_tipoDeSinalItemStateChanged

        if (this.cmbx_tipoDeSinal.getSelectedIndex() == 0) {
            //this.lbl_amplitude.setVisible(false);
            this.lbl_offset.setVisible(false);
            this.lbl_periodo.setVisible(false);
            //this.txtF_amplitude.setVisible(false);
            this.txtF_offset.setVisible(false);
            this.txtF_Periodo.setVisible(false);
            this.txtF_Periodo.setText("20");

            this.simulatorConection.setSignalType(0);

        }

        if (this.cmbx_tipoDeSinal.getSelectedIndex() == 1) {
            //this.lbl_amplitude.setVisible(true);
            this.lbl_offset.setVisible(true);
            this.lbl_periodo.setVisible(true);
            //this.txtF_amplitude.setVisible(true);
            this.txtF_offset.setVisible(true);
            this.txtF_Periodo.setVisible(true);

            this.simulatorConection.setSignalType(1);

        }

        if (this.cmbx_tipoDeSinal.getSelectedIndex() == 2) {
            //this.lbl_amplitude.setVisible(true);
            this.lbl_offset.setVisible(true);
            this.lbl_periodo.setVisible(true);
            //this.txtF_amplitude.setVisible(true);
            this.txtF_offset.setVisible(true);
            this.txtF_Periodo.setVisible(true);

            this.simulatorConection.setSignalType(2);

        }

        if (this.cmbx_tipoDeSinal.getSelectedIndex() == 3) {
            //this.lbl_amplitude.setVisible(true);
            this.lbl_offset.setVisible(true);
            this.lbl_periodo.setVisible(true);
            //this.txtF_amplitude.setVisible(true);
            this.txtF_offset.setVisible(true);
            this.txtF_Periodo.setVisible(true);

            this.simulatorConection.setSignalType(3);

        }

        if (this.cmbx_tipoDeSinal.getSelectedIndex() == 4) {
            //this.lbl_amplitude.setVisible(true);
            this.lbl_offset.setVisible(true);
            this.lbl_periodo.setVisible(true);
            //this.txtF_amplitude.setVisible(true);
            this.txtF_offset.setVisible(true);
            this.txtF_Periodo.setVisible(true);

            this.simulatorConection.setSignalType(4);

        }


    }//GEN-LAST:event_cmbx_tipoDeSinalItemStateChanged

    private void btn_refreshMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_btn_refreshMouseClicked

        if (!this.simulatorConection.isConnectionStatus()) {

            String ip;
            int porta, canalW, canalR;

            ip = this.txtF_ip.getText();
            porta = Integer.parseInt(this.txtF_porta.getText());
            canalW = this.formManager.whichChannelIsUsedtoWrite(channel1_Write, channel2_Write, channel3_Write, channel4_Write, channel5_Write, channel6_Write, channel7_Write, channel8_Write);
            String status;
            boolean sucess = false;
            boolean canais[] = new boolean[8];

            canais[0] = this.channel1_Read.isSelected();
            canais[1] = this.channel2_Read.isSelected();
            canais[2] = this.channel3_Read.isSelected();
            canais[3] = this.channel4_Read.isSelected();
            canais[4] = this.channel5_Read.isSelected();
            canais[5] = this.channel6_Read.isSelected();
            canais[6] = this.channel7_Read.isSelected();
            canais[7] = this.channel8_Read.isSelected();
            //canalR = this.formManager.whichChannelIsUsedtoRead(channel1_Read, channel2_Read, channel3_Read, channel4_Read, channel5_Read, channel6_Read, channel7_Read, channel8_Read);

            this.simulatorConection.refreshConnection(ip, porta, canalW, 0, this.txtF_amplitude,
                    this.txtF_offset, this.txtF_Periodo, 0, transit, canais);


            if (this.simulatorConection.isConnectionStatus()) {
                this.lbl_configuracoes_conexao.setText("Sistema Conectado");
                this.txtF_ip.setEnabled(false);
                this.txtF_porta.setEnabled(false);

                this.channel1_Read.setEnabled(false);
                this.channel2_Read.setEnabled(false);
                this.channel3_Read.setEnabled(false);
                this.channel4_Read.setEnabled(false);
                this.channel5_Read.setEnabled(false);
                this.channel6_Read.setEnabled(false);
                this.channel7_Read.setEnabled(false);
                this.channel8_Read.setEnabled(false);

                this.channel1_Write.setEnabled(false);
                this.channel2_Write.setEnabled(false);
                this.channel3_Write.setEnabled(false);
                this.channel4_Write.setEnabled(false);
                this.channel5_Write.setEnabled(false);
                this.channel6_Write.setEnabled(false);
                this.channel7_Write.setEnabled(false);
                this.channel8_Write.setEnabled(false);

                if (canalW == 0) {
                    this.lbl_conexao_Escrita0.setText("Canal 0: Habilitado");
                }

                if (canalW == 1) {
                   this.lbl_conexao_Escrita1.setText("Canal 1: Habilitado"); 
                }

                if (canalW == 2) {
                    this.lbl_conexao_Escrita2.setText("Canal 2: Habilitado");
                }

                if (canalW == 3) {
                    this.lbl_conexao_Escrita3.setText("Canal 3: Habilitado");
                }

                if (canalW == 4) {
                    this.lbl_conexao_Escrita4.setText("Canal 4: Habilitado");
                }

                if (canalW == 5) {
                    this.lbl_conexao_Escrita5.setText("Canal 5: Habilitado");
                }

                if (canalW == 6) {
                    this.lbl_conexao_Escrita6.setText("Canal 6: Habilitado");
                }

                if (canalW == 7) {
                    this.lbl_conexao_Escrita7.setText("Canal 7: Habilitado");
                }

                if (canais[0]) {
                    this.lbl_conexao_leitura0.setText("Canal 0: Habilitado");
                }

                if (canais[1]) {
                    this.transit[16] = 2;
                    this.lbl_conexao_leitura1.setText("Canal 1: Habilitado");
                }

                if (canais[2]) {
                    
                    this.lbl_conexao_leitura2.setText("Canal 2: Habilitado");
                }

                if (canais[3]) {
                    this.lbl_conexao_leitura3.setText("Canal 3: Habilitado");
                }

                if (canais[4]) {
                    this.lbl_conexao_leitura4.setText("Canal 4: Habilitado");
                }

                if (canais[5]) {
                    this.lbl_conexao_leitura5.setText("Canal 5: Habilitado");
                }

                if (canais[6]) {
                    this.lbl_conexao_leitura6.setText("Canal 6: Habilitado");
                }

                if (canais[7]) {
                    this.lbl_conexao_leitura7.setText("Canal 7: Habilitado");
                }

            }


        }





    }//GEN-LAST:event_btn_refreshMouseClicked

    private void txtF_amplitudeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF_amplitudeKeyReleased

        /*
         * try { double aux = Double.parseDouble(this.txtF_amplitude.getText());
         * } catch (Exception e) { }
         */

        this.simulatorConection.conversionAmplitude();
//        if (this.simulatorConection.getAltura() > 27 && this.simulatorConection.getValor() > 1.3) {
//            if (this.simulatorConection.getTensionValue() > 1.3) {
//                this.txtF_amplitude.setText("1.3");
//            }
//        }





    }//GEN-LAST:event_txtF_amplitudeKeyReleased

    private void txtF_offsetKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF_offsetKeyReleased
        this.simulatorConection.conversionOffset();
    }//GEN-LAST:event_txtF_offsetKeyReleased

    private void txtF_PeriodoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF_PeriodoKeyReleased
        this.simulatorConection.conversionPeriodo();
    }//GEN-LAST:event_txtF_PeriodoKeyReleased

    private void jButton1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton1MouseClicked
        if (this.simulatorConection.isConnectionStatus()) {
            if (aux) {
                this.simulatorConection.turnOffSystem();
                this.lbl_ONOFF.setText("Sistema Desligada");
                aux = false;
            } else {
                this.grafoManager.myClear();
                this.simulatorConection.conversionAmplitude();
                this.simulatorConection.conversionOffset();
                this.simulatorConection.conversionPeriodo();
                this.simulatorConection.turnOnSystem();

                this.lbl_ONOFF.setText("Sistema Ligado");
                aux = true;
                //this.simulatorConection.start();
            }
        } else {
            JOptionPane.showMessageDialog(rootPane, "Sistema sem conexão", "Tank Simulator", JOptionPane.OK_CANCEL_OPTION);
        }
    }//GEN-LAST:event_jButton1MouseClicked

    private void jButton2MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jButton2MouseClicked
        this.grafoManager.myClear2();
    }//GEN-LAST:event_jButton2MouseClicked

    private void channel1_ReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_channel1_ReadActionPerformed
        this.formManager.validateReadChannel(channel1_Read, channel2_Read, channel3_Read, channel4_Read, channel5_Read, channel6_Read, channel7_Read, channel8_Read, channel1_Read);
    }//GEN-LAST:event_channel1_ReadActionPerformed

    private void channel2_ReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_channel2_ReadActionPerformed
        this.formManager.validateReadChannel(channel1_Read, channel2_Read, channel3_Read, channel4_Read, channel5_Read, channel6_Read, channel7_Read, channel8_Read, channel2_Read);
    }//GEN-LAST:event_channel2_ReadActionPerformed

    private void channel3_ReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_channel3_ReadActionPerformed
        this.formManager.validateReadChannel(channel1_Read, channel2_Read, channel3_Read, channel4_Read, channel5_Read, channel6_Read, channel7_Read, channel8_Read, channel3_Read);
    }//GEN-LAST:event_channel3_ReadActionPerformed

    private void channel4_ReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_channel4_ReadActionPerformed
        this.formManager.validateReadChannel(channel1_Read, channel2_Read, channel3_Read, channel4_Read, channel5_Read, channel6_Read, channel7_Read, channel8_Read, channel4_Read);
    }//GEN-LAST:event_channel4_ReadActionPerformed

    private void channel5_ReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_channel5_ReadActionPerformed
        this.formManager.validateReadChannel(channel1_Read, channel2_Read, channel3_Read, channel4_Read, channel5_Read, channel6_Read, channel7_Read, channel8_Read, channel5_Read);
    }//GEN-LAST:event_channel5_ReadActionPerformed

    private void channel6_ReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_channel6_ReadActionPerformed
        this.formManager.validateReadChannel(channel1_Read, channel2_Read, channel3_Read, channel4_Read, channel5_Read, channel6_Read, channel7_Read, channel8_Read, channel6_Read);
    }//GEN-LAST:event_channel6_ReadActionPerformed

    private void channel7_ReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_channel7_ReadActionPerformed
        this.formManager.validateReadChannel(channel1_Read, channel2_Read, channel3_Read, channel4_Read, channel5_Read, channel6_Read, channel7_Read, channel8_Read, channel7_Read);
    }//GEN-LAST:event_channel7_ReadActionPerformed

    private void channel8_ReadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_channel8_ReadActionPerformed
        this.formManager.validateReadChannel(channel1_Read, channel2_Read, channel3_Read, channel4_Read, channel5_Read, channel6_Read, channel7_Read, channel8_Read, channel8_Read);
    }//GEN-LAST:event_channel8_ReadActionPerformed

    private void txtF_setPointKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtF_setPointKeyReleased
        this.simulatorConection.conversionSetpoint(this.txtF_setPoint);
    }//GEN-LAST:event_txtF_setPointKeyReleased

    private void pnl_GraficoSinalMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_GraficoSinalMouseClicked
        this.pnl_GraficoALtura.setVisible(false);
        this.pnl_erroAltura.setVisible(false);
        this.pnl_nivelTanque2.setVisible(false);
        this.pnl_grafico_todos.setVisible(false);
        System.out.println("dkfbdhjbdfjhgbd");
    }//GEN-LAST:event_pnl_GraficoSinalMouseClicked

    private void pnl_grafico_todosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_pnl_grafico_todosMouseClicked
        JOptionPane.showMessageDialog(null, "teste");
    }//GEN-LAST:event_pnl_grafico_todosMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /*
         * Set the Nimbus look and feel
         */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /*
         * If Nimbus (introduced in Java SE 6) is not available, stay with the
         * default look and feel. For details see
         * http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainForm.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /*
         * Create and display the form
         */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                new MainForm().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton Radio_ClosedSystem;
    private javax.swing.JRadioButton Radio_OpenSytem;
    private javax.swing.JButton btn_refresh;
    private javax.swing.JRadioButton channel1_Read;
    private javax.swing.JRadioButton channel1_Write;
    private javax.swing.JRadioButton channel2_Read;
    private javax.swing.JRadioButton channel2_Write;
    private javax.swing.JRadioButton channel3_Read;
    private javax.swing.JRadioButton channel3_Write;
    private javax.swing.JRadioButton channel4_Read;
    private javax.swing.JRadioButton channel4_Write;
    private javax.swing.JRadioButton channel5_Read;
    private javax.swing.JRadioButton channel5_Write;
    private javax.swing.JRadioButton channel6_Read;
    private javax.swing.JRadioButton channel6_Write;
    private javax.swing.JRadioButton channel7_Read;
    private javax.swing.JRadioButton channel7_Write;
    private javax.swing.JRadioButton channel8_Read;
    private javax.swing.JRadioButton channel8_Write;
    private javax.swing.JComboBox cmbx_tipoDeSinal;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTabbedPane jTabbedPane2;
    private javax.swing.JLabel lbl_Malha;
    private javax.swing.JLabel lbl_ONOFF;
    private javax.swing.JLabel lbl_amplitude;
    private javax.swing.JLabel lbl_canalDeEscrita;
    private javax.swing.JLabel lbl_canalDeLeitura;
    private javax.swing.JLabel lbl_conexao_Escrita0;
    private javax.swing.JLabel lbl_conexao_Escrita1;
    private javax.swing.JLabel lbl_conexao_Escrita2;
    private javax.swing.JLabel lbl_conexao_Escrita3;
    private javax.swing.JLabel lbl_conexao_Escrita4;
    private javax.swing.JLabel lbl_conexao_Escrita5;
    private javax.swing.JLabel lbl_conexao_Escrita6;
    private javax.swing.JLabel lbl_conexao_Escrita7;
    private javax.swing.JLabel lbl_conexao_leitura0;
    private javax.swing.JLabel lbl_conexao_leitura1;
    private javax.swing.JLabel lbl_conexao_leitura2;
    private javax.swing.JLabel lbl_conexao_leitura3;
    private javax.swing.JLabel lbl_conexao_leitura4;
    private javax.swing.JLabel lbl_conexao_leitura5;
    private javax.swing.JLabel lbl_conexao_leitura6;
    private javax.swing.JLabel lbl_conexao_leitura7;
    private javax.swing.JLabel lbl_configuracoes_conexao;
    private javax.swing.JLabel lbl_configuracoes_ip;
    private javax.swing.JLabel lbl_configuracoes_porta;
    private javax.swing.JLabel lbl_fatorDeAceleracao;
    private javax.swing.JLabel lbl_grafico;
    private javax.swing.JLabel lbl_nivel;
    private javax.swing.JLabel lbl_offset;
    private javax.swing.JLabel lbl_periodo;
    private javax.swing.JLabel lbl_saida_erro_centimetro;
    private javax.swing.JLabel lbl_saida_nivel_centimetro;
    private javax.swing.JLabel lbl_saida_tempo_segundo;
    private javax.swing.JLabel lbl_saida_tensao_volts;
    private javax.swing.JLabel lbl_setPoint;
    private javax.swing.JLabel lbl_sinal;
    private javax.swing.JLabel lbl_tempo;
    private javax.swing.JLabel lbl_tensao;
    private javax.swing.JPanel panel_Escrita;
    private javax.swing.JPanel panel_canalDeLeitura;
    private javax.swing.JPanel pnl_GraficoALtura;
    private javax.swing.JPanel pnl_GraficoSinal;
    private javax.swing.JPanel pnl_Grafico_SinalApenas;
    private javax.swing.JPanel pnl_Grafico_fundoAba1;
    private javax.swing.JPanel pnl_Grafico_fundoAba2;
    private javax.swing.JPanel pnl_erroAltura;
    private javax.swing.JPanel pnl_grafico_aba1;
    private javax.swing.JPanel pnl_grafico_todos;
    private javax.swing.JPanel pnl_malha;
    private javax.swing.JPanel pnl_nivelTanque2;
    private javax.swing.JTextField txtF_Periodo;
    private javax.swing.JTextField txtF_amplitude;
    private javax.swing.JTextField txtF_errorAltura;
    private javax.swing.JTextField txtF_fatorAceleracao;
    private javax.swing.JTextField txtF_ip;
    private javax.swing.JTextField txtF_offset;
    private javax.swing.JTextField txtF_porta;
    private javax.swing.JTextField txtF_setPoint;
    private javax.swing.JTextField txtF_tempo;
    private javax.swing.JTextField txtF_valorNivel;
    private javax.swing.JTextField txtF_valorNivelTanque2;
    private javax.swing.JTextField txtF_valorTensao;
    // End of variables declaration//GEN-END:variables
}
